name:                advent-of-code-Y2020
version:             0.1.0.0
github:              "michaelwebb76/advent-of-code-2020"
license:             BSD3
author:              "Michael Webb"
maintainer:          "michaelwebb76@gmail.com"
copyright:           "2020 Michael Webb"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Proper Chrimbo

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  advent-of-code-2020-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-of-code-Y2020
